PF4Public/gentoo-overlay

- www-client/ungoogled-chromium-bin/ungoogled-chromium-bin-84.0.4147.89_p1.ebuild
ungoogled-chromium-bin-84 will still depend on libopenh264.so.4 even after reinstall
> www-client/ungoogled-chromium-bin: depend on exact package slots

- www-client/ungoogled-chromium/files/chromium-93-ffmpeg-4.4.patch
- www-client/ungoogled-chromium/ungoogled-chromium-93.0.4577.63-r1.ebuild
Currently it's not possible to build ungoogled-chromium-93 with ffmpeg 4.4 (and possibly 4.3). This pull request should make it possible to build ungoogled-chromium-93 with ffmpeg-4.3+ (future versions should also be supported).
Alternatively you could use a simpler approach Arch folks [took](https://aur.archlinux.org/cgit/aur.git/tree/chromium-93-ffmpeg-4.4.patch?h=chromium-no-extras), but it only supports ffmpeg 4.3 and 4.4, but it's not future proof (eg. ffmpeg 4.5 will not work).
When this gets accepted/merged probably we could make system-ffmpeg default again.
> www-client/ungoogled-chromium-93 Allow to build with ffmpeg 4.3/4.4

- www-client/ungoogled-chromium/files/chromium-cfi-clang13-back-compat.patch
- www-client/ungoogled-chromium/ungoogled-chromium-93.0.4577.63-r1.ebuild
Fix building Chromium>=93 with Clang<13 due to Clang 13 deprecating
'-fsanitize-blacklist' in favor of '-fsanitize-ignorelist'
Closes #100
> www-client/ungoogled-chromium: fix CFI build with clang<13

- www-client/ungoogled-chromium-bin/ungoogled-chromium-bin-97.0.4692.71.ebuild
This PR fixs the dev-libs/jsoncpp error mentiond in #124.
I tested with my gentoo setup.
```bash
>>> Emerging (3 of 3) www-client/ungoogled-chromium-bin-97.0.4692.71::pf4public
* ungoogled-chromium-bin-97.0.4692.71-x86-64.tar.bz2 BLAKE2B SHA512 size ;-) ...      [ ok ]
* Determining the location of the kernel source code
* Found kernel source directory:
*     /usr/src/linux
* Found sources for kernel version:
*     5.15.11-gentoo-x86_64
>>> Unpacking source...
>>> Unpacking ungoogled-chromium-bin-97.0.4692.71-x86-64.tar.bz2 to /var/tmp/portage/www-client/ungoogled-chromium-bin-97.0.4692.71/work
>>> Source unpacked in /var/tmp/portage/www-client/ungoogled-chromium-bin-97.0.4692.71/work
>>> Preparing source in /var/tmp/portage/www-client/ungoogled-chromium-bin-97.0.4692.71/work ...
>>> …
```
> www-client/ungoogled-chromium-bin: update dev-libs/jsoncpp (fix #124)

- www-client/ungoogled-chromium/files/chromium-wayland-fixed-terminate-caused-by-binding-to-wrong-version.patch
- www-client/ungoogled-chromium/ungoogled-chromium-97.0.4692.99-r1.ebuild
Upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1279574
Upstream patch: https://chromium-review.googlesource.com/c/chromium/src/+/3337037
Fixes: #129
> www-client/ungoogled-chromium: fix startup crash on wlroots>=0.15.0

- dev-util/electron/electron-17.0.1-r1.ebuild
- dev-util/electron/electron-17.1.0.ebuild
- dev-util/electron/files/ppc64le/fixes/libpng-pdfium-compile-98.patch
Segfaults, do not merge yet.
```
$ electron-17
Electron 17.0.1 - Build cross platform desktop apps with JavaScript, HTML, and CSS
Usage: electron [options] [path]
A path to an Electron app may be specified. It must be one of the following:
- index.js file.
- Folder containing a package.json file.
- Folder containing an index.js file.
- .html/.htm file.
- http://, https://, or file:// URL.
Options:
-i, --interactive     Open a REPL to the main process.
-r, --require         Module to preload (option can be repeated).
-v, --version         Print the version.
-a, --abi             Print the Node ABI version.
[471643:0227/000628.467204:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is egl, ANGLE is 
[471643:0227/000628.472150:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called …
```
> feat(electron:17): ppc64le support

- www-client/ungoogled-chromium/ungoogled-chromium-99.0.4844.45-r1.ebuild
- www-client/ungoogled-chromium/ungoogled-chromium-99.0.4844.51-r1.ebuild
Let's remove the ~ppc64 keyword from chromium 99 for the moment.
For the future I think it would be safer to preemptively remove the keyword from new major versions until I have the chance to test it, because chances of breakage are high unfortunately.
Damn I hate Chrome so much: not only they didn't merge ppc64le support despite being offered build servers for CI, they didn't even care to reply.
> fix(ungoogled-chromium-99): remove ppc64 keyword

- dev-util/electron/electron-16.0.9.ebuild
- dev-util/electron/files/electron_node_collections_abc_py310.patch
fix to use collections.abc needed for py310 compat
> dev-util/electron: fix collections.abc for py310

- dev-util/electron/electron-17.1.2.ebuild
I think you can safely keep keywords for minor releases and maybe remove it once the major version of Chromium changes.
> feat(electron-17.1.2): ppc64 keyword

- app-editors/vscode/vscode-1.66.2.ebuild
- app-editors/vscode/vscode-1.67.0.ebuild
- app-editors/vscode/vscode-9999.ebuild
node module webpack shall not use legacy hash md4
see workaround at https://github.com/webpack/webpack/issues/14560
> fix: build with openssl3

- dev-util/electron/files/ppc64le/fix-breakpad-compile.patch
It was erroneously removed in a previous commit.
> fix(electron-19): add missing fix-breakpad-compile.patch

- net-im/element-desktop/element-desktop-1.11.4.ebuild
- net-im/element-desktop/element-desktop-1.11.5.ebuild
- net-im/element-desktop/element-desktop-9999.ebuild
Closes: #170 
This adds a custom build step for building `app.asar` for ppc64, due to `electron-builder` not supporting architectures other than x86 and arm. This step should be self-contained, and other architectures will use `electron-builder` as before.
Production dependencies are currently installed again in this step, due to requiring all dependencies for typescript to compile some files in a prior step and hoisting production dependencies from the full set being a non-trivial task. A better solution might be possible, but this works for now.
> net-im/element-desktop: Fix build on ppc64

- www-client/ungoogled-chromium/ungoogled-chromium-107.0.5304.121_p1.ebuild
- www-client/ungoogled-chromium/ungoogled-chromium-108.0.5359.48_p1.ebuild
- www-client/ungoogled-chromium/ungoogled-chromium-108.0.5359.71_p1.ebuild
Hello,
I’ve set `enable_mse_mpeg2ts_stream_parser` dependent on `proprietary-codecs` USE as it is throwing an error in configure if not set to false when `proprietary-codecs` is disabled.
I’ve also added a required USE on `!proprietary-codecs` to `!hevc` since `hevc` USE need `proprietary-codecs`.
> www-client/ungoogled-chromium: fix configure for [-proprietary-codecs]

- net-im/element-desktop/element-desktop-9999.ebuild
Script changed from javascript to typescript, update the ebuild accordingly.
Signed off by Joe Kappus <joe@wt.gd>
> Fix element-desktop-9999 build.

- www-client/ungoogled-chromium-bin/ungoogled-chromium-bin-109.0.5414.74.ebuild
Hello,
After https://github.com/PF4Public/gentoo-overlay/commit/e46cbcd6a0796b66e88ccf0541a78b33a7150c6e there are still some IUSE flags to be removed in the ebuild: `core2` and `haswell`.
Thanks.
```
ERROR: pretend
ERROR: www-client/ungoogled-chromium-bin-109.0.5414.74::pf4public failed (pretend phase):
USE Flag 'core2' not in IUSE for www-client/ungoogled-chromium-bin-109.0.5414.74
Call stack:
ebuild.sh, line 136:  Called pkg_pretend
ungoogled-chromium-bin-109.0.5414.74.ebuild, line 127:  Called use 'core2'
phase-helpers.sh, line 256:  Called die
```
> www-client/ungoogled-chromium-bin-109.0.5414.74: remove unused IUSE flags

- dev-util/electron/electron-22.3.11.ebuild
- dev-util/electron/electron-22.3.12.ebuild
- dev-util/electron/files/gcc-13/gcc-13-angle-ShaderVars.patch
- dev-util/electron/files/gcc-13/gcc-13-base.patch
- dev-util/electron/files/gcc-13/gcc-13-cc-targetproperty.patch
- dev-util/electron/files/gcc-13/gcc-13-components.patch
- dev-util/electron/files/gcc-13/gcc-13-dawn.patch
- dev-util/electron/files/gcc-13/gcc-13-documentattachmentinfo.patch
- dev-util/electron/files/gcc-13/gcc-13-encounteredsurfacetracker.patch
- dev-util/electron/files/gcc-13/gcc-13-gcc-incomplete-type-v8-subtype.patch
- dev-util/electron/files/gcc-13/gcc-13-gpu_feature_info.patch
- dev-util/electron/files/gcc-13/gcc-13-maldoca.patch
- dev-util/electron/files/gcc-13/gcc-13-misc.patch
- dev-util/electron/files/gcc-13/gcc-13-net.patch
- dev-util/electron/files/gcc-13/gcc-13-openscreen.patch
- dev-util/electron/files/gcc-13/gcc-13-pdfium.patch
- dev-util/electron/files/gcc-13/gcc-13-perfetto-uuid.patch
- dev-util/electron/files/gcc-13/gcc-13-quiche.patch
- dev-util/electron/files/gcc-13/gcc-13-ruy.patch
- dev-util/electron/files/gcc-13/gcc-13-s2cellid.patch
- dev-util/electron/files/gcc-13/gcc-13-swiftshader.patch
- dev-util/electron/files/gcc-13/gcc-13-tensorflow-tflite.patch
- dev-util/electron/files/gcc-13/gcc-13-vulkanmemoryallocator.patch
- dev-util/electron/files/gcc-13/gcc-13-webrtc.patch
Add support for gcc-13, so electron builds with gcc-13 installed.
> Electron 22.3.8 support for gcc-13

- www-client/ungoogled-chromium/files/chromium-118-ffmpeg.patch
- www-client/ungoogled-chromium/ungoogled-chromium-118.0.5993.54_p1.ebuild
This should adjust ffmpeg patch for `ungoogled-chromium-118` (final build to confirm everything works as expected still in progress)
> Fix ffmpeg patch for ungoogled-chromium-118

- net-im/element-web/element-web-9999.ebuild
This is not needed anymore with >=openssl 3.0, it breaks the build now.
This reverts commit 96573cca36e0f8898d1b73eb9a0cdfbf5bbe2931.
> Revert "net-im/element-web: openssl >=3.0; #194"

- dev-util/electron/electron-29.4.0.ebuild
> dev-util/electron-29.4.0: enable py3.12

- net-im/element-desktop/element-desktop-1.11.66.ebuild
Tested building with 3.12, works fine. Updated copyright to this year too.
> net-im/element-desktop: enable py3.12

- www-client/opera/opera-12.16_p1860-r1.ebuild
I hope it keeps your "pre"-logic functional but I tried my best to port the old versionator-calls to the new (and now required) `ver_*` functions as described here: https://mgorny.pl/articles/the-ultimate-guide-to-eapi-7.html#replacing-versionator-eclass-uses
This fixes #357
> www-client/opera: bump to EAPI 8

- www-client/ungoogled-chromium/files/chromium-127-separate-qt56.patch
- www-client/ungoogled-chromium/ungoogled-chromium-127.0.6533.88_p1.ebuild
The patch posted to https://issues.chromium.org/issues/328182252#comment3 decouples the QT5 dependency when building a QT6-only build.   Tested on my QT6-only Gentoo system and it works without issue.
> www-client/ungoogled-chromium: Allow building against QT6 without depending on QT5

- www-client/ungoogled-chromium/files/chromium-system-av1.patch
- www-client/ungoogled-chromium/files/chromium-system-libvpx.patch
- www-client/ungoogled-chromium/ungoogled-chromium-137.0.7151.55_p1.ebuild
This patch adds support for system-av1. Tested using the website [HTML5 audio/video tester](https://tools.woolyss.com/html5-audio-video-tester/?u=woolyss.com/f/av1-opus-sita.webm)
> add a patch for system-av1

- www-client/ungoogled-chromium/files/chromium-system-abseil.patch
- www-client/ungoogled-chromium/ungoogled-chromium-137.0.7151.103_p1.ebuild
So I worked on system-abseil-cpp patches and got it in working condition. At least on GCC, I haven't tested it with clang yet.
Here is proof that it indeed links to abseil:
```bash
philmb@aliens ~ $ ldd /usr/lib64/chromium-browser/chrome | ag absl
libabsl_raw_logging_internal.so.2505.0.0 => /usr/lib64/libabsl_raw_logging_internal.so.2505.0.0 (0x000073979d18a000)
libabsl_spinlock_wait.so.2505.0.0 => /usr/lib64/libabsl_spinlock_wait.so.2505.0.0 (0x000073979d185000)
libabsl_cord.so.2505.0.0 => /usr/lib64/libabsl_cord.so.2505.0.0 (0x000073979d167000)
libabsl_cordz_info.so.2505.0.0 => /usr/lib64/libabsl_cordz_info.so.2505.0.0 (0x000073979d15d000)
libabsl_cord_internal.so.2505.0.0 => /usr/lib64/libabsl_cord_internal.so.2505.0.0 (0x000073979d149000)
libabsl_synchronization.so.2505.0.0 => …
```
> system-abseil-cpp: fix this patch.

- www-client/ungoogled-chromium/files/chromium-138-gcc.patch
* Reduce g++ memory usage at the cost of less verbose error messages.
This sets "-ftrack-macro-expansion=0".
Using this option makes the preprocessor and the compiler consume more memory. Memory tracking defaults to 2.
Please see documentation for more information, https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html
* Move "-Wno-changes-meaning" (C++) to CXXFLAGS.
> www-client/ungoogled-chromium: adjust gcc flags.
